#!/usr/bin/env bash
#
# The script checks consistency across FreeIPA servers.
# Put BIND password in to ipa_check_consistency.passwd file to stop password
# prompts.
#
# Copyright (C) 2017 Peter Pakos <peter.pakos@wandisco.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -eo pipefail
IFS=$'\n'

readonly APP_VER="1.0.1"
readonly APP_NAME="$(basename "$0")"
readonly APP_DIR="$(cd "$(dirname "$0")" && pwd)"
readonly TMP_DIR="$(mktemp -d)"
# shellcheck disable=SC2034,SC2155
declare PASSWD_FILE="${APP_DIR}/$(basename "$0").passwd"
declare -a SERVERS=()
declare DOMAIN=""
declare SUFFIX=""
declare BINDDN="cn=Directory Manager"
declare BINDPW=""
declare NAGIOSREPORT=""
declare -i FIRST_COLUMN=20
declare -i MIDDLE_COLUMNS=5
declare -i LAST_COLUMN=5
declare -i NAGIOS=0
declare WARNING=1
declare CRITICAL=2
declare -a NAGIOSOPTS=("all" "users" "ustage" "upres" "ugroups" "hosts" "hgroups" "hbac" "sudo" "zones" "certs" "ldap" "ghosts" "bind")
declare -A NAGIOSMSGS=( \
                        ['users']='Active Users' \
                        ['ustage']='Stage Users' \
                        ['upres']='Preserved Users'
                        ['ugroups']='User Groups' \
                        ['hosts']='Hosts' \
                        ['hgroups']='Host Groups' \
                        ['hbac']='HBAC Rules' \
                        ['sudo']='SUDO Rules' \
                        ['zones']='DNS Zones' \
                        ['certs']='Certificates' \
                        ['ldap']='LDAP Conflicts' \
                        ['ghosts']='Ghost Replicas' \
                        ['bind']='Anonymous BIND' \
                      )
declare -i CHECKS_NO=${#NAGIOSMSGS[@]}

die() {
  local msg="${1:-}"
  local -i code=${2:-1}

  if [[ -n "$msg" ]]; then
    printf "%s\n" "$msg" >&2
  fi

  exit "$code"
}

display_version() {
  printf "%s version %s\n" "$APP_NAME" "$APP_VER"
}

display_help() {
  display_version
  cat <<HELP
Usage: ${APP_NAME} [OPTIONS]
AVAILABLE OPTIONS:
-H  List of IPA servers (e.g.: "server1 server2.domain server3")
    Both short names and FQDNs are supported (FQDN if not within IPA domain)
-d  IPA domain (e.g.: "ipa.domain.com")
-s  LDAP root suffix, if not domain based (default: "dc=ipa,dc=domain,dc=com")
-D  BIND DN (default: cn=Directory Manager)
-W  BIND password (prompt for one if not supplied)
-p  Password file (default: $(basename "$0").passwd)
-n  Nagios plugin mode
    all     - all checks (-w and -c only relevant if -na used), default if incorrect value is passed
    users   - Active Users
    ustage  - Stage Users
    upres   - Preserved Users
    ugroups - User Groups
    hosts   - Hosts
    hgroups - Host Groups
    hbac    - HBAC Rules
    sudo    - SUDO Rules
    zones   - DNS Zones
    certs   - Certificates
    ldap    - LDAP Conflicts
    ghosts  - Ghost Replicas
    bind    - Anonymous BIND
-w  Warning threshold (0-${CHECKS_NO}), number of failed checks before alerting (default: 1)
-c  Critical threshold (0-${CHECKS_NO}), number of failed checks before alerting (default: 2)
-h  Print this help summary page
-v  Print version number
HELP
}

contains() {
  local n=$#
  local value=${!n}

  for ((i=1;i < $#;i++)) {
    if [[ "${!i}" == "${value}" ]]; then
      printf "y\n"
      return 0
    fi
  }
  printf "n\n"
  return 1
}

get_opts() {
  while getopts ":vhd:D:W:s:p:H:n:w:c:" opt; do
    case $opt in
      v)
        display_version
        exit 0
        ;;
      h)
        display_help
        exit 0
        ;;
      d)
        DOMAIN="${OPTARG,,}"
        ;;
      D)
        BINDDN="${OPTARG}"
        ;;
      W)
        BINDPW="${OPTARG}"
        ;;
      s)
        SUFFIX="${OPTARG}"
        ;;
      p)
        PASSWD_FILE="${OPTARG}"
        if [[ ! -r "$PASSWD_FILE" ]]; then
          die "Unable to open password file ${PASSWD_FILE}, exiting."
        fi
        ;;
      H)
        IFS=" "
        SERVERS=($OPTARG)
        IFS=$'\n'
        update_cols
        ;;
      n)
        NAGIOS=1
        if [[ $(contains "${NAGIOSOPTS[@]}" "${OPTARG}") == "y" ]]; then
          NAGIOSREPORT="${OPTARG}"
        else
          NAGIOSREPORT="all"
        fi
        ;;
      w)
        WARNING="${OPTARG}"
        ;;
      c)
        CRITICAL="${OPTARG}"
        ;;
      :)
        die "Option -${OPTARG} requires an argument"
        ;;
      *)
        die "Invalid option -${OPTARG}"
        ;;
    esac
  done
}

is_integer() {
  local var="$1"

  if [[ "$var" =~ ^[-+]?[0-9]+$ ]]; then
    return 0
  else
    return 1
  fi
}

get_hosts() {
  local domain="$1" hosts=""

  if type dig &>/dev/null; then
    hosts=$(dig +short "_ldap._tcp.${domain}" SRV | awk '{print $4}')
  elif type nslookup &>/dev/null; then
    hosts=$(nslookup -q=SRV "_ldap._tcp.${domain}" | awk '/_ldap._tcp./ {print $7}')
  else
    hosts=$(host -t SRV "_ldap._tcp.${domain}" | awk '{print $8}')
  fi

  if printf "%s" "$(sed -e "s/\.$//" <<<"$hosts" | sort | xargs)"; then
    return 0
  else
    printf "Failed while detecting IPA servers in LDAP\n" >&2
    return 1
  fi
}

check_vars() {
  local -i fail=0 i=0

  if [[ -z "$DOMAIN" ]]; then
    printf "IPA domain not specified (-d)\n" >&2
    fail=1
  else
    if [[ -z "$SUFFIX" ]]; then
      SUFFIX="dc=${DOMAIN//./,dc=}"
    fi
  fi

  if [[ ${#SERVERS[@]} -lt 1 ]]; then
    IFS=" "
    SERVERS=($(get_hosts "$DOMAIN"))
    IFS=$'\n'
    if [[ ${#SERVERS[@]} -lt 1 ]]; then
      printf "Hosts not specified with -H and not found in LDAP\n" >&2
      fail=1
    else
      update_cols
    fi
  fi

  if is_integer "$WARNING"; then
    if ! [[ $WARNING -ge 0 && $WARNING -le $CHECKS_NO ]]; then
      printf "Warning threshold (-w) needs to be an integer between 1 and %i\n" "$CHECKS_NO" >&2
      fail=1
    fi
  else
    printf "Warning threshold (-w) needs to be an integer\n" >&2
    fail=1
  fi
  if is_integer "$CRITICAL"; then
    if ! [[ $CRITICAL -ge 0 && $CRITICAL -le $CRITICAL ]]; then
      printf "Critical threshold (-c) needs to be an integer between 1 and %i\n" "$CHECKS_NO" >&2
      fail=1
    fi
  else
    printf "Critical threshold (-w) needs to be an integer\n" >&2
    fail=1
  fi
  if is_integer "$CRITICAL" && is_integer "$WARNING"; then
    if ! [[ $CRITICAL -ge $WARNING ]]; then
      printf "Critical threshold (-c) needs to be greater than warning threshold (-w)\n" >&2
      fail=1
    fi
  fi

  if [[ $fail -ne 0 ]]; then
    die
  fi
  for ((i=0; i<${#SERVERS[@]}; i++)); do
    if ! [[ "${SERVERS[i]}" =~ \. ]]; then
      SERVERS[i]="${SERVERS[i]}.${DOMAIN}"
    fi
  done
}

get_pass() {
  if [[ -z "$BINDPW" ]]; then
    if [[ -r "$PASSWD_FILE" ]]; then
      BINDPW="$(<"$PASSWD_FILE")"
    else
      printf "%s password: " "${BINDDN#cn=}"
      read -rs BINDPW
      printf "\n"
    fi
  fi
}

validate_pass() {
  for server in "${SERVERS[@]}"; do
  if ldapwhoami -ZZ -x -h "$server" -D "$BINDDN" -w "$BINDPW" &>/dev/null; then
    return 0
  fi
  done
  die "BIND failed to all servers, check connection details and try again."
}

hr() {
  local -i len=$(( FIRST_COLUMN + ${#SERVERS[@]} * MIDDLE_COLUMNS + LAST_COLUMN ))
  local -i i=0

  for((i=1; i<=len; i++)); do
    printf "="
  done
  printf "\n"
}

display_header() {
  local server=""

  printf "%-${FIRST_COLUMN}s" "FreeIPA servers:"
  for server in "${SERVERS[@]}"; do
    server="${server%%.*}"
    printf "%-${MIDDLE_COLUMNS}s" "$server"
  done
  printf "%-${LAST_COLUMN}s\n" "STATE"
  hr
}

is_consistent() {
  local dir="$1"

  # shellcheck disable=SC2046
  if diff --from-file $(grep -lv 'N/A' -r "$dir" || printf "%s" "$dir") &>/dev/null; then
    printf "OK"
  else
    printf "FAIL"
  fi
}

query_ldap() {
  local base="$1"
  local filter="$2"
  local attr="$3"
  local scope="${4:-sub}"

  ldapsearch -o ldif-wrap=no -ZZ -LLLx -h "${server}" \
    -D "$BINDDN" -w "$BINDPW" -s "$scope" \
    -b "$base" "$filter" "$attr" 2>/dev/null

  return $?
}

active_users() {
  local server="" count="" state=""
  local dir="${TMP_DIR}/active_users"

  mkdir -p "$dir"
  printf "%-${FIRST_COLUMN}s" "Active Users"
  for server in "${SERVERS[@]}"; do
    (
    if ! count=$(query_ldap "cn=users,cn=accounts,${SUFFIX}" \
      "(objectClass=*)" "numSubordinates" "base" \
      | awk '/numSubordinates: / {print $2}'); then
      count="ERROR"
    fi
    printf "%s" "$count" > "${dir}/${server}"
    ) &
  done
  wait
  for server in "${SERVERS[@]}"; do
    printf "%-${MIDDLE_COLUMNS}s" "$(< "${dir}/${server}")"
  done
  state="$(is_consistent "$dir")"
  printf "%-${LAST_COLUMN}s\n" "$state"
  if [[ $NAGIOS -eq 1 ]]; then
    printf "%s\n" "$state" >> "${TMP_DIR}/nagios"
    if [[ "$NAGIOSREPORT" == "users" ]]; then
      printf "%s\n" "$state" >> "${TMP_DIR}/$NAGIOSREPORT"
    fi
  fi
}

staged_users() {
  local server="" count="" state=""
  local dir="${TMP_DIR}/staged_users"

  mkdir -p "$dir"
  printf "%-${FIRST_COLUMN}s" "Stage Users"
  for server in "${SERVERS[@]}"; do
    (
    if ! count=$(query_ldap \
      "cn=staged users,cn=accounts,cn=provisioning,${SUFFIX}" \
      "(objectClass=*)" "numSubordinates" "base" \
      | awk '/numSubordinates: / {print $2}'); then
      count="ERROR"
    fi
    printf "%s" "$count" > "${dir}/${server}"
    ) &
  done
  wait
  for server in "${SERVERS[@]}"; do
    printf "%-${MIDDLE_COLUMNS}s" "$(< "${dir}/${server}")"
  done
  state="$(is_consistent "$dir")"
  printf "%-${LAST_COLUMN}s\n" "$state"
  if [[ $NAGIOS -eq 1 ]]; then
    printf "%s\n" "$state" >> "${TMP_DIR}/nagios"
    if [[ "$NAGIOSREPORT" == "ustage" ]]; then
      printf "%s\n" "$state" >> "${TMP_DIR}/$NAGIOSREPORT"
    fi
  fi
}

preserved_users() {
  local server="" count="" state=""
  local dir="${TMP_DIR}/preserved_users"

  mkdir -p "$dir"
  printf "%-${FIRST_COLUMN}s" "Preserved Users"
  for server in "${SERVERS[@]}"; do
    (
    if ! count=$(query_ldap \
      "cn=deleted users,cn=accounts,cn=provisioning,${SUFFIX}" \
      "(objectClass=*)" "numSubordinates" "base" \
      | awk '/numSubordinates: / {print $2}'); then
      count="ERROR"
    fi
    printf "%s" "$count" > "${dir}/${server}"
    ) &
  done
  wait
  for server in "${SERVERS[@]}"; do
    printf "%-${MIDDLE_COLUMNS}s" "$(< "${dir}/${server}")"
  done
  state="$(is_consistent "$dir")"
  printf "%-${LAST_COLUMN}s\n" "$state"
  if [[ $NAGIOS -eq 1 ]]; then
    printf "%s\n" "$state" >> "${TMP_DIR}/nagios"
    if [[ "$NAGIOSREPORT" == "upres" ]]; then
      printf "%s\n" "$state" >> "${TMP_DIR}/$NAGIOSREPORT"
    fi
  fi
}

groups() {
  local server="" count="" state=""
  local dir="${TMP_DIR}/groups"

  mkdir -p "$dir"
  printf "%-${FIRST_COLUMN}s" "User Groups"
  for server in "${SERVERS[@]}"; do
    (
    if ! count=$(query_ldap "cn=groups,cn=accounts,${SUFFIX}" \
      "(objectClass=ipausergroup)" "dn" "one"); then
      count="ERROR"
    else
      count=$(grep -c "^dn:" <<<"$count" || true)
    fi
    printf "%s" "$count" > "${dir}/${server}"
    ) &
  done
  wait
  for server in "${SERVERS[@]}"; do
    printf "%-${MIDDLE_COLUMNS}s" "$(< "${dir}/${server}")"
  done
  state="$(is_consistent "$dir")"
  printf "%-${LAST_COLUMN}s\n" "$state"
  if [[ $NAGIOS -eq 1 ]]; then
    printf "%s\n" "$state" >> "${TMP_DIR}/nagios"
    if [[ "$NAGIOSREPORT" == "ugroups" ]]; then
      printf "%s\n" "$state" >> "${TMP_DIR}/$NAGIOSREPORT"
    fi
  fi
}

hosts() {
  local server="" count="" state=""
  local dir="${TMP_DIR}/nhosts"

  mkdir -p "$dir"
  printf "%-${FIRST_COLUMN}s" "Hosts"
  for server in "${SERVERS[@]}"; do
    (
    if ! count=$(query_ldap "cn=computers,cn=accounts,${SUFFIX}" \
      "(objectClass=*)" "numSubordinates" "base" \
      | awk '/numSubordinates: / {print $2}'); then
      count="ERROR"
    fi
    printf "%s" "$count" > "${dir}/${server}"
    ) &
  done
  wait
  for server in "${SERVERS[@]}"; do
    printf "%-${MIDDLE_COLUMNS}s" "$(< "${dir}/${server}")"
  done
  state="$(is_consistent "$dir")"
  printf "%-${LAST_COLUMN}s\n" "$state"
  if [[ $NAGIOS -eq 1 ]]; then
    printf "%s\n" "$state" >> "${TMP_DIR}/nagios"
    if [[ "$NAGIOSREPORT" == "hosts" ]]; then
      printf "%s\n" "$state" >> "${TMP_DIR}/$NAGIOSREPORT"
    fi
  fi
}

hostgroups() {
  local server="" count="" state=""
  local dir="${TMP_DIR}/hostgroups"

  mkdir -p "$dir"
  printf "%-${FIRST_COLUMN}s" "Host Groups"
  for server in "${SERVERS[@]}"; do
    (
    if ! count=$(query_ldap "cn=hostgroups,cn=accounts,${SUFFIX}" \
      "(objectClass=*)" "numSubordinates" "base" \
      | awk '/numSubordinates: / {print $2}'); then
      count="ERROR"
    fi
    printf "%s" "$count" > "${dir}/${server}"
    ) &
  done
  wait
  for server in "${SERVERS[@]}"; do
    printf "%-${MIDDLE_COLUMNS}s" "$(< "${dir}/${server}")"
  done
  state="$(is_consistent "$dir")"
  printf "%-${LAST_COLUMN}s\n" "$state"
  if [[ $NAGIOS -eq 1 ]]; then
    printf "%s\n" "$state" >> "${TMP_DIR}/nagios"
    if [[ "$NAGIOSREPORT" == "hgroups" ]]; then
      printf "%s\n" "$state" >> "${TMP_DIR}/$NAGIOSREPORT"
    fi
  fi
}

hbac_rules() {
  local server="" count="" state=""
  local dir="${TMP_DIR}/hbac_rules"

  mkdir -p "$dir"
  printf "%-${FIRST_COLUMN}s" "HBAC Rules"
  for server in "${SERVERS[@]}"; do
    (
    if ! count=$(query_ldap "cn=hbac,${SUFFIX}" \
      "(ipaUniqueID=*)" "dn" "one"); then
      count="ERROR"
    else
      count=$(grep -c "^dn:" <<<"$count" || true)
    fi
    printf "%s" "$count" > "${dir}/${server}"
    ) &
  done
  wait
  for server in "${SERVERS[@]}"; do
    printf "%-${MIDDLE_COLUMNS}s" "$(< "${dir}/${server}")"
  done
  state="$(is_consistent "$dir")"
  printf "%-${LAST_COLUMN}s\n" "$state"
  if [[ $NAGIOS -eq 1 ]]; then
    printf "%s\n" "$state" >> "${TMP_DIR}/nagios"
    if [[ "$NAGIOSREPORT" == "hbac" ]]; then
      printf "%s\n" "$state" >> "${TMP_DIR}/$NAGIOSREPORT"
    fi
  fi
}

sudo_rules() {
  local server="" count="" first_column="" state=""
  local dir="${TMP_DIR}/sudo_rules"

  mkdir -p "$dir"
  printf "%-${FIRST_COLUMN}s" "SUDO Rules"
  for server in "${SERVERS[@]}"; do
    (
    if ! count=$(query_ldap "cn=sudorules,cn=sudo,${SUFFIX}" \
      "(ipaUniqueID=*)" "dn" "one"); then
      count="ERROR"
    else
      count=$(grep -c "^dn:" <<<"$count" || true)
    fi
    printf "%s" "$count" > "${dir}/${server}"
    ) &
  done
  wait
  for server in "${SERVERS[@]}"; do
    printf "%-${MIDDLE_COLUMNS}s" "$(< "${dir}/${server}")"
  done
  state="$(is_consistent "$dir")"
  printf "%-${LAST_COLUMN}s\n" "$state"
  if [[ $NAGIOS -eq 1 ]]; then
    printf "%s\n" "$state" >> "${TMP_DIR}/nagios"
    if [[ "$NAGIOSREPORT" == "sudo" ]]; then
      printf "%s\n" "$state" >> "${TMP_DIR}/$NAGIOSREPORT"
    fi
  fi
}

dns_zones() {
  local server="" count="" state=""
  local dir="${TMP_DIR}/dns_zones"

  mkdir -p "$dir"
  printf "%-${FIRST_COLUMN}s" "DNS Zones"
  for server in "${SERVERS[@]}"; do
    (
    if ! count=$(query_ldap "cn=dns,${SUFFIX}" \
      "(|(objectClass=idnszone)(objectClass=idnsforwardzone))" \
      "dn" "one"); then
      count="ERROR"
    else
      count=$(grep -c "^dn:" <<<"$count" || true)
    fi
    printf "%s" "$count" > "${dir}/${server}"
    ) &
  done
  wait
  for server in "${SERVERS[@]}"; do
    printf "%-${MIDDLE_COLUMNS}s" "$(< "${dir}/${server}")"
  done
  state="$(is_consistent "$dir")"
  printf "%-${LAST_COLUMN}s\n" "$state"
  if [[ $NAGIOS -eq 1 ]]; then
    printf "%s\n" "$state" >> "${TMP_DIR}/nagios"
    if [[ "$NAGIOSREPORT" == "zones" ]]; then
      printf "%s\n" "$state" >> "${TMP_DIR}/$NAGIOSREPORT"
    fi
  fi
}

certificates() {
  local server="" count="" state=""
  local dir="${TMP_DIR}/certificates"

  mkdir -p "$dir"
  printf "%-${FIRST_COLUMN}s" "Certificates"
  for server in "${SERVERS[@]}"; do
    (
    if ! count=$(query_ldap "ou=certificateRepository,ou=ca,o=ipaca" \
      "(certStatus=*)" \
      "dn" "one"); then
      count="N/A"
    else
      count=$(grep -c "^dn:" <<<"$count" || true)
    fi
    printf "%s" "$count" > "${dir}/${server}"
    ) &
  done
  wait
  for server in "${SERVERS[@]}"; do
    printf "%-${MIDDLE_COLUMNS}s" "$(< "${dir}/${server}")"
  done
  state="$(is_consistent "$dir")"
  printf "%-${LAST_COLUMN}s\n" "$state"
  if [[ $NAGIOS -eq 1 ]]; then
    printf "%s\n" "$state" >> "${TMP_DIR}/nagios"
    if [[ "$NAGIOSREPORT" == "certs" ]]; then
      printf "%s\n" "$state" >> "${TMP_DIR}/$NAGIOSREPORT"
    fi
  fi
}

ldap_conflicts() {
  local server="" conflicts="" state="" consistent=""
  local dir="${TMP_DIR}/ldap_conflicts"

  mkdir -p "$dir"
  printf "%-${FIRST_COLUMN}s" "LDAP Conflicts"
  for server in "${SERVERS[@]}"; do
    (
    if ! conflicts=$(query_ldap "${SUFFIX}" "(nsds5ReplConflict=*)" \
      "nsds5ReplConflict"); then
      conflicts="ERROR"
    else
      if [[ -n "$conflicts" ]]; then
        conflicts="YES"
      else
        conflicts="NO"
      fi
    fi
    printf "%s" "$conflicts" > "${dir}/${server}"
    ) &
  done
  wait
  for server in "${SERVERS[@]}"; do
    printf "%-${MIDDLE_COLUMNS}s" "$(< "${dir}/${server}")"
  done
  consistent="$(is_consistent "$dir")"
  conflicts="$(<"${dir}/${SERVERS[0]}")"
  if [[ "$consistent" == "OK" && "$conflicts" == "NO" ]]; then
    state="OK"
  else
    state="FAIL"
  fi
  printf "%-${LAST_COLUMN}s\n" "$state"
  if [[ $NAGIOS -eq 1 ]]; then
    printf "%s\n" "$state" >> "${TMP_DIR}/nagios"
    if [[ "$NAGIOSREPORT" == "ldap" ]]; then
      printf "%s\n" "$state" >> "${TMP_DIR}/$NAGIOSREPORT"
    fi
  fi
}

anon_bind() {
  local server="" state=""
  local dir="${TMP_DIR}/anon_bind"

  mkdir -p "$dir"
  printf "%-${FIRST_COLUMN}s" "Anonymous BIND"
  for server in "${SERVERS[@]}"; do
    (
    if ! state=$(query_ldap "cn=config" "(cn=config)" \
      "nsslapd-allow-anonymous-access" \
      | awk '/nsslapd-allow-anonymous-access: / {print $2}'); then
      state="ERROR"
    fi
    if [[ "$state" == "on" ]]; then
      state="YES"
    elif [[ "$state" == "off" ]]; then
      state="NO"
    fi
    printf "%s" "$state" > "${dir}/${server}"
    ) &
  done
  wait
  for server in "${SERVERS[@]}"; do
    printf "%-${MIDDLE_COLUMNS}s" "$(< "${dir}/${server}")"
  done
  state="$(is_consistent "$dir")"
  printf "%-${LAST_COLUMN}s\n" "$state"
  if [[ $NAGIOS -eq 1 ]]; then
    printf "%s\n" "$state" >> "${TMP_DIR}/nagios"
    if [[ "$NAGIOSREPORT" == "bind" ]]; then
      printf "%s\n" "$state" >> "${TMP_DIR}/$NAGIOSREPORT"
    fi
  fi
}

replication() {
  local server="" agreements="" agreement="" state=""
  local -i i=0 max=0
  local dir="${TMP_DIR}/replication"
  # shellcheck disable=SC2155
  local suffix="$(sed -e 's@=@\\3D@g' -e 's@,@\\,@g' <<<"$SUFFIX")"

  mkdir -p "$dir"
  for server in "${SERVERS[@]}"; do
    (
    if ! agreements=$(query_ldap \
      "cn=replica,cn=${suffix},cn=mapping tree,cn=config" \
      "nsDS5ReplicaHost" "nsds5replicaLastUpdateStatus" "one" \
      | sed -e 's/Error (//' -e 's/)//' \
      | awk '{if ($0 ~ /nsDS5ReplicaHost/) printf("%s",$2); if ($0 ~ /nsds5replicaLastUpdateStatus/) printf(" %s\n",$2)}' \
      | sed -e "s/\.${DOMAIN}//g"); then
      agreements="ERROR"
    fi
    for agreement in $agreements; do
      printf "%s\n" "$agreement" >>"${dir}/${server}"
    done
    ) &
  done
  wait
  for server in "${SERVERS[@]}"; do
    if [[ -r "${dir}/${server}" ]]; then
      n=$(wc -l < "${dir}/${server}")
    else
      n=0
    fi
    [[ $n -gt $max ]] && max=$n
  done
  for ((i=1; i<=max; i++)); do
    [[ $i -eq 1 ]] && first_column="Replication Status" || first_column=""
    printf "%-${FIRST_COLUMN}s" "$first_column"
    for server in "${SERVERS[@]}"; do
      if [[ -s "${dir}/${server}" ]]; then
        line=$(sed -n '1p' "${dir}/${server}")
        sed -i -e '1d' "${dir}/${server}"
      else
        line=""
      fi
      printf "%-${MIDDLE_COLUMNS}s" "$line"
      if [[ "$line" == "ERROR" ]]; then
        state="FAIL"
      fi
    done
    printf "%-${LAST_COLUMN}s\n" "$state"
  done
}

ghost_replicas() {
  local server="" ghost_replicas="" state="" consistent=""
  local dir="${TMP_DIR}/ghost_replicas"

  mkdir -p "$dir"
  printf "%-${FIRST_COLUMN}s" "Ghost Replicas"
  for server in "${SERVERS[@]}"; do
    (
    if ! ghost_replicas=$(\
      query_ldap "${SUFFIX}" "(&(objectclass=nstombstone)(nsUniqueId=ffffffff-ffffffff-ffffffff-ffffffff))" \
      "nscpentrywsi" \
      | grep nsds50ruv \
      | grep 'replica '); then
      ghost_replicas="ERROR"
    else
      ghost_replicas=$(grep -vc ldap <<<"$ghost_replicas" || true)
      if [[ $ghost_replicas -eq 0 ]]; then
        ghost_replicas="NO"
      fi
    fi
    printf "%s" "$ghost_replicas" > "${dir}/${server}"
    ) &
  done
  wait
  for server in "${SERVERS[@]}"; do
    printf "%-${MIDDLE_COLUMNS}s" "$(< "${dir}/${server}")"
  done
  consistent="$(is_consistent "$dir")"
  ghost_replicas="$(<"${dir}/${SERVERS[0]}")"
  if [[ "$consistent" == "OK" && "$ghost_replicas" == "NO" ]]; then
    state="OK"
  else
    state="FAIL"
  fi
  printf "%-${LAST_COLUMN}s\n" "$state"
  if [[ $NAGIOS -eq 1 ]]; then
    printf "%s\n" "$state" >> "${TMP_DIR}/nagios"
    if [[ "$NAGIOSREPORT" == "ghosts" ]]; then
      printf "%s\n" "$state" >> "${TMP_DIR}/$NAGIOSREPORT"
    fi
  fi
}

update_cols() {
  local -i max=0

  for server in "${SERVERS[@]}"; do
    server="${server%%.*}"
    [[ ${#server} -gt $max ]] && max=${#server}
  done
  max=$((max+4))
  if [[ $max -gt $MIDDLE_COLUMNS ]]; then
    MIDDLE_COLUMNS=$max
  fi
}

query_servers() {
  active_users > "$TMP_DIR/active_users.out" &
  staged_users > "$TMP_DIR/staged_users.out" &
  preserved_users > "$TMP_DIR/preserved_users.out" &
  groups > "$TMP_DIR/groups.out" &
  hosts > "$TMP_DIR/nhosts.out" &
  hostgroups > "$TMP_DIR/hostgroups.out" &
  hbac_rules > "$TMP_DIR/hbac_rules.out" &
  sudo_rules > "$TMP_DIR/sudo_rules.out" &
  dns_zones > "$TMP_DIR/dns_zones.out" &
  certificates > "$TMP_DIR/certificates.out" &
  ldap_conflicts > "$TMP_DIR/ldap_conflicts.out" &
  anon_bind > "$TMP_DIR/anon_bind.out" &
  replication > "$TMP_DIR/replication.out" &
  ghost_replicas > "$TMP_DIR/ghost_replicas.out" &
  wait
}

display_data() {
  printf "%s\n" "$(< "${TMP_DIR}/active_users.out")"
  printf "%s\n" "$(< "${TMP_DIR}/staged_users.out")"
  printf "%s\n" "$(< "${TMP_DIR}/preserved_users.out")"
  printf "%s\n" "$(< "${TMP_DIR}/groups.out")"
  printf "%s\n" "$(< "${TMP_DIR}/nhosts.out")"
  printf "%s\n" "$(< "${TMP_DIR}/hostgroups.out")"
  printf "%s\n" "$(< "${TMP_DIR}/hbac_rules.out")"
  printf "%s\n" "$(< "${TMP_DIR}/sudo_rules.out")"
  printf "%s\n" "$(< "${TMP_DIR}/dns_zones.out")"
  printf "%s\n" "$(< "${TMP_DIR}/certificates.out")"
  printf "%s\n" "$(< "${TMP_DIR}/ldap_conflicts.out")"
  printf "%s\n" "$(< "${TMP_DIR}/ghost_replicas.out")"
  printf "%s\n" "$(< "${TMP_DIR}/anon_bind.out")"
  printf "%s\n" "$(< "${TMP_DIR}/replication.out")"
}

cleanup() {
  rm -rf "$TMP_DIR"
}

nagios_check() {
  local msg=""
  local -i code=3

  if [[ "$NAGIOSREPORT" == "all" ]]; then
    # shellcheck disable=SC2155
    local -i oks=$(grep -c "OK" "${TMP_DIR}/nagios")
    local -i fails=$(( CHECKS_NO - oks ))
    if [[ $fails -ge 0 && $fails -lt $WARNING ]]; then
      msg="OK"
      code=0
    elif [[ $fails -ge $WARNING && $fails -lt $CRITICAL ]]; then
      msg="WARNING"
      code=1
    elif [[ $fails -ge $CRITICAL ]]; then
      msg="CRITICAL"
      code=2
    else
      msg="UNKNOWN"
      code=3
    fi
    msg="${msg} - ${oks}/${CHECKS_NO} checks passed"
    printf "%s\n" "$msg"
    cleanup
    exit $code
  else
    # shellcheck disable=SC2155
    local -i oks=$(grep -c "OK" "${TMP_DIR}/$NAGIOSREPORT")
    if [[ $oks -eq 1 ]]; then
      msg="OK"
      code=0
    else
      msg="CRITICAL"
      code=2
    fi
    msg="${msg} - ${NAGIOSMSGS[$NAGIOSREPORT]}"
    printf "%s\n" "$msg"
    cleanup
    exit $code
  fi
}

main() {
  get_opts "$@"
  check_vars
  get_pass
  validate_pass
  if [[ $NAGIOS -eq 0 ]]; then
    display_header
  fi
  query_servers
  if [[ $NAGIOS -eq 1 ]]; then
    nagios_check
  else
    display_data
    hr
  fi
  cleanup
}

main "$@"
