#!/usr/bin/env bash

set -euo pipefail

if [[ "$@" == "test" ]]; then
  test="test"
else
  test=""
fi

for f in *.md; do
  pandoc -s -f gfm -t rst "$f" > "${f%.md}.rst"
done

python setup.py "${test}release" || true

for f in *.md; do
  rm -f "${f%.md}.rst"
done
